query getResumeInput($filter: resume_caseFilter) {
  resume_caseCollection(filter: $filter) {
    edges {
      node {
        id
        name
        resume_case_inputCollection {
          edges {
            node {
              input_id
              case_id
              resume_input {
                max
                min
                name
                regex
                requirement
                type
              }
            }
          }
        }
      }
    }
  }
}
