mutation updateResumeSubmittedAt($set: resumeUpdateInput!, $filter: resumeFilter) {
  updateresumeCollection(set: $set, filter: $filter) {
    records {
      submitted_at
    }
  }
}

mutation createResume($userId: UUID!, $caseId: Int!) {
  insertIntoresumeCollection(objects: { user_id: $userId, case_id: $caseId }) {
    records {
      user_id
      case_id
    }
  }
}

query getResumeCase($teamId: String) {
  resume_caseCollection(filter: { name: { eq: $teamId } }) {
    edges {
      node {
        id
        name
      }
    }
  }
}

query getResumeWithInputAndAnswers($userId: UUID!, $caseId: Int) {
  resumeCollection(filter: { user_id: { eq: $userId }, case_id: { eq: $caseId } }) {
    edges {
      node {
        id
        case_id
        user_id
        submitted_at

        resume_case {
          id
          name
          resume_case_inputCollection {
            edges {
              node {
                case_id
                input_id
                resume_input {
                  id
                  max
                  min
                  name
                  type
                  regex
                  requirement
                }
              }
            }
          }
        }

        resume_answerCollection {
          edges {
            node {
              id
              value
              input_id
              resume_id
            }
          }
        }
      }
    }
  }
}
